[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/mod.rs"

[dependencies.log]
version = "0.4"

[dependencies.daku]
git = "https://github.com/ardaku/daku.git"
rev = "44aabf7"
features = ["log", "prompt"]
