[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/mod.rs"

[dependencies.log]
version = "0.4"

[dependencies.daku]
version = "0.5"
features = ["log", "prompt"]

[dependencies.rlsf]
version = "0.2"
